[build]
  base = "./"
  publish = "_docs3"
  command = "yarn build:3.x"
  # This sort of lets us build only on tagged commits to prod
  # [context.production]
  #   ignore = "if git diff $CACHED_COMMIT_REF $COMMIT_REF ./package.json | grep - | grep version && git diff $CACHED_COMMIT_REF $COMMIT_REF ./package.json | grep + | grep version; then exit 1; else exit 0; fi"

# Sets our asset optimization
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true

# Caches our images for 1 year
[[headers]]
  for = "/images/*"
  [headers.values]
	  Cache-Control = "public, max-age=31536000"

# Domain redirects
[[redirects]]
  from = "https://docs.lndo.io/*"
  to = "https://docs.lando.dev/:splat"
  status = 301
[[redirects]]
  from = "https://docs.devwithlando.io/*"
  to = "https://docs.lando.dev/:splat"
  status = 301

# Legacy redirects from cloudflare
[[redirects]]
  from = "https://docs.lando.dev/contrib/how.html"
  to = "https://docs.lando.dev/contrib/contributing.html"
  status = 301
[[redirects]]
  from = "https://docs.lando.dev/issues/*"
  to = "https://docs.lando.dev/help/:splat"
  status = 301
[[redirects]]
  from = "https://docs.lando.dev/tutorials/*"
  to = "https://docs.lando.dev/config/:splat"
  status = 301
[[redirects]]
  from = "https://docs.lando.dev/dev/*"
  to = "https://docs.lando.dev/contrib/:splat"
  status = 301
[[redirects]]
  from = "https://docs.lando.dev/started.html"
  to = "https://docs.lando.dev/basics/"
  status = 301
[[redirects]]
  from = "https://docs.lando.dev/installation/*"
  to = "https://docs.lando.dev/basics/installation.html"
  status = 301
[[redirects]]
  from = "https://docs.lando.dev/cli/*"
  to = "https://docs.lando.dev/basics/:splat"
  status = 301
[[redirects]]
  from = "https://docs.lando.dev/troubleshooting/*"
  to = "https://docs.devwithlando.io/help/:splat"
  status = 301
[[redirects]]
  from = "https://docs.lando.dev/config/config.html"
  to = "https://docs.lando.dev/config/global.html"
  status = 301
  
# Stitch together the various plugin subsites
[[redirects]]
  from = "/acquia/*"
  to = "https://lando-acquia.netlify.app/:splat"
  status = 200
[[redirects]]
  from = "/dotnet/*"
  to = "https://lando-dotnet.netlify.app/:splat"
  status = 200
[[redirects]]
  from = "/go/*"
  to = "https://lando-go.netlify.app/:splat"
  status = 200
[[redirects]]
  from = "/lagoon/*"
  to = "https://lando-lagoon.netlify.app/:splat"
  status = 200
[[redirects]]
  from = "/mssql/*"
  to = "https://lando-mssql.netlify.app/:splat"
  status = 200
[[redirects]]
  from = "/node/*"
  to = "https://lando-node.netlify.app/:splat"
  status = 200
[[redirects]]
  from = "/pantheon/*"
  to = "https://lando-pantheon.netlify.app/:splat"
  status = 200
[[redirects]]
  from = "/php/*"
  to = "https://lando-php.netlify.app/:splat"
  status = 200
[[redirects]]
  from = "/platformsh/*"
  to = "https://lando-platformsh.netlify.app/:splat"
  status = 200
[[redirects]]
  from = "/python/*"
  to = "https://lando-python.netlify.app/:splat"
  status = 200
[[redirects]]
  from = "/ruby/*"
  to = "https://lando-ruby.netlify.app/:splat"
  status = 200

# Redirect the legacy pages
# [[redirects]]
#   from = "https://docs.lando.dev/config/acquia.html"
#   to = "https://docs.lando.dev/acquia"
#   status = 301
# [[redirects]]
#   from = "https://docs.lando.dev/config/dotnet.html"
#   to = "https://docs.lando.dev/dotnet"
# [[redirects]]
#   from = "https://docs.lando.dev/config/go.html"
#   to = "https://docs.lando.dev/go"
#   status = 301
# [[redirects]]
#   from = "https://docs.lando.dev/config/lagoon.html"
#   to = "https://docs.lando.dev/lagoon"
#   status = 301
# [[redirects]]
#   from = "https://docs.lando.dev/config/mssql.html"
#   to = "https://docs.lando.dev/mssql"
#   status = 301
# [[redirects]]
#   from = "https://docs.lando.dev/config/node.html"
#   to = "https://docs.lando.dev/node"
#   status = 301
# [[redirects]]
#   from = "https://docs.lando.dev/config/pantheon.html"
#   to = "https://docs.lando.dev/pantheon"
#   status = 301
# [[redirects]]
#   from = "https://docs.lando.dev/config/platformsh.html"
#   to = "https://docs.lando.dev/platformsh"
#   status = 301
# [[redirects]]
#   from = "https://docs.lando.dev/config/php.html"
#   to = "https://docs.lando.dev/php"
#   status = 301
# [[redirects]]
#   from = "https://docs.lando.dev/config/python.html"
#   to = "https://docs.lando.dev/python"
#   status = 301
# [[redirects]]
#   from = "https://docs.lando.dev/config/ruby.html"
#   to = "https://docs.lando.dev/ruby"
#   status = 301
